// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkHmADftjLSyPFREtI9gJ4fizMkQ67zO8',
    appId: '1:1075792667630:web:63a6479e171b0d23d524ff',
    messagingSenderId: '1075792667630',
    projectId: 'spotify-jvb',
    authDomain: 'spotify-jvb.firebaseapp.com',
    storageBucket: 'spotify-jvb.appspot.com',
    measurementId: 'G-0LCWW5ETE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALP_qtFyWKCHU43QJVzfgGwOajInR6ilE',
    appId: '1:1075792667630:android:14d1c523d56e7968d524ff',
    messagingSenderId: '1075792667630',
    projectId: 'spotify-jvb',
    storageBucket: 'spotify-jvb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBREKv-d9aCaqUXYM4RgzCM1NMcHS_Qj3s',
    appId: '1:1075792667630:ios:86db7dfcd9f251ccd524ff',
    messagingSenderId: '1075792667630',
    projectId: 'spotify-jvb',
    storageBucket: 'spotify-jvb.appspot.com',
    iosClientId: '1075792667630-5vvba3eo9c1sdpa2b22h6sl7gja9d46b.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBREKv-d9aCaqUXYM4RgzCM1NMcHS_Qj3s',
    appId: '1:1075792667630:ios:86db7dfcd9f251ccd524ff',
    messagingSenderId: '1075792667630',
    projectId: 'spotify-jvb',
    storageBucket: 'spotify-jvb.appspot.com',
    iosClientId: '1075792667630-5vvba3eo9c1sdpa2b22h6sl7gja9d46b.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkHmADftjLSyPFREtI9gJ4fizMkQ67zO8',
    appId: '1:1075792667630:web:b0eb8afd71e6f509d524ff',
    messagingSenderId: '1075792667630',
    projectId: 'spotify-jvb',
    authDomain: 'spotify-jvb.firebaseapp.com',
    storageBucket: 'spotify-jvb.appspot.com',
    measurementId: 'G-QJ3CT5XFBL',
  );

}